// Completion is a participant-facing service screen. Keep it separate from
// the response-document frame so a record can remain in its source language
// while this surrounding interface follows the selected interface language.
const copy = {
  ko: {
    brand: "〈만 39세 이상〉 · 참여 기록", title: "당신의 기록을 남깁니다", lead: "여기 적힌 기억과 지금의 이야기를 오래 살펴보겠습니다.", print: "인쇄·PDF 저장", retry: "저장 다시 확인", restart: "다른 사람이 새로 시작하기", referral: "다음 참여자에게 프로젝트 전하기",
    status: { confirmed: "당신의 기록을 연구 자료로 저장했어요.", sending: "참여 기록을 연구 자료로 저장하고 있어요.", unverified: "저장을 요청했지만, 저장 여부는 아직 확인하지 못했습니다. 기록 사본은 이 기기에 남아 있습니다.", local_only: "참여 기록을 이 기기에 저장했습니다.", failed: "아직 연구 저장소에 저장되지 않았습니다. 「저장 다시 확인」을 눌러주세요." },
    audienceLead: "이 문서에는 관객의 기억과 판단, 다시 찾고 싶은 마음과 참여 조건이 함께 담겼어요.", otherLead: "이 문서는 문화예술의 현재를 기록하는 자료로 이어집니다.",
    openCallBadge: "2026년 12월 · 모호주택", openCallTitle: "공모", openCallText: "2026년 12월 · 모호주택에서 함께할 작업을 기다립니다.", openCallButton: "공모 보기",
    greetingBrand: "안부의 좌표", greetingTitle: "서로 다른 기록 사이에 안부를 남깁니다", greetingStored: "참여자가 맡긴 안부는 설문 응답과 분리해 보관하고 64개의 좌표를 따라 큐레이션합니다. 이름과 이메일은 서로에게 공개하지 않습니다.", greetingPreparing: "안부의 좌표는 64개의 좌표를 따라 한 번의 만남을 큐레이션하는 방식으로 준비하고 있습니다. 이름과 이메일은 서로에게 공개하지 않습니다.", greetingReason: "세 방향과 64개의 좌표는 기록이 어떻게 이어지고 달라졌는지, 어떤 조건과 만나는지를 읽고 왜 한 안부가 당신에게 닿았는지 설명하는 데 사용합니다.", greetingEmailLead: "안부를 받고 싶다면 이메일을 남겨주세요.", greetingReadyBefore: "새 안부나 답장이 도착하면 ", greetingReadyAfter: " 이름으로 알림을 보냅니다. 메일 첫 문단에서 프로젝트 안부라는 점과 수신 이유를 설명하고, 메시지는 편지 화면에서 열어봅니다.", greetingPending: "안부 전달이 시작되면 발신 계정과 서버 메일 큐가 연결된 뒤 알림을 보냅니다.", greetingAction: "도착한 안부 보고 다음 안부 남기기", greetingClosed: "안부의 좌표 운영 조건이 확정되면 이곳에서 시작합니다.",
  },
  en: {
    brand: "〈Over 39〉 · PARTICIPATION RECORD", title: "We keep your record", lead: "We will stay a long time with the memories and the present-day stories written here.", print: "Print or save as PDF", retry: "Check saving again", restart: "Start fresh for another person", referral: "Tell the next participant about the project",
    status: { confirmed: "Your record has been saved as research material.", sending: "Saving your participation record as research material.", unverified: "We sent the request, but we have not been able to confirm it yet. A copy of the record is still on this device.", local_only: "The participation record is saved on this device.", failed: "The record has not reached the research archive yet. Please press “Check again”." },
    audienceLead: "This document holds an audience member’s memories and judgements, their wish to return, and the conditions for taking part.", otherLead: "This document becomes part of a record of arts and culture as they are now.",
    openCallBadge: "December 2026 · Moho House", openCallTitle: "Open call", openCallText: "December 2026 · We are waiting for the work we will share at Moho House.", openCallButton: "View open call",
    greetingBrand: "Coordinates of Greeting", greetingTitle: "Leave a greeting between different records", greetingStored: "Greetings entrusted by participants are kept separately from survey responses and curated along the 64 coordinates. Names and email addresses are never shared between participants.", greetingPreparing: "Coordinates of Greeting is being prepared as a way of curating one single encounter along the 64 coordinates. Names and email addresses are never shared between participants.", greetingReason: "The three directions and 64 coordinates are used to read how your record carries on, how it has changed, and what conditions it meets — and to explain why one greeting reached you.", greetingEmailLead: "Leave an email address if you would like to receive a greeting.", greetingReadyBefore: "If a new greeting or reply arrives, we will send a notice from ", greetingReadyAfter: "Notices are sent under this name. The first paragraph of the email explains that this is a greeting from the project and why it reached you; the message itself opens on a letter page.", greetingPending: "When greetings begin to go out, we will send a notice once the sending account and the server’s mail queue are connected.", greetingAction: "See an arrived greeting or leave one", greetingClosed: "Coordinates of Greeting will start here once the arrangements for running it are settled.",
  },
  ja: {
    brand: "〈39歳以上〉・参加記録", title: "あなたの記録を残します", lead: "ここに書かれた記憶と今のお話を、これから長く読み続けていきます。", print: "印刷・PDF保存", retry: "保存をもう一度確認", restart: "別の人が新しく始める", referral: "次の参加者にプロジェクトを伝える",
    status: { confirmed: "記録を研究資料として保存しました。", sending: "参加記録を研究資料として保存しています。", unverified: "保存の手続きは始まりましたが、完了はまだ確認できていません。記録の控えは、この端末に残っています。", local_only: "参加記録をこの端末に保存しました。", failed: "研究用の保管先には、まだ保存されていません。「保存を再確認」を押してください。" },
    audienceLead: "この文書には、観客としての記憶と判断、もう一度訪れたい気持ち、参加を支える条件がともに収められています。", otherLead: "この文書は、文化芸術の今を記録する資料の一つになります。",
    openCallBadge: "2026年12月・モホハウス", openCallTitle: "公募", openCallText: "2026年12月・モホハウスで、ともにつくる作品をお待ちしています。", openCallButton: "公募を見る",
    greetingBrand: "挨拶の座標", greetingTitle: "異なる記録のあいだに挨拶を残します", greetingStored: "参加者から預かったあいさつは調査の回答とは分けて保管し、64の座標をたどってお届けする相手を選びます。名前とメールアドレスが参加者どうしに公開されることはありません。", greetingPreparing: "あいさつの座標は、64の座標をたどって一度の出会いを選ぶしくみとして準備中です。名前とメールアドレスが参加者どうしに公開されることはありません。", greetingReason: "三つの方向と64の座標は、記録がどのように続き、どう変わったのか、どの条件と出会うのかを読み、なぜこのあいさつがあなたに届いたのかを説明するために使います。", greetingEmailLead: "あいさつを受け取りたい場合は、メールアドレスを書いてください。", greetingReadyBefore: "新しい挨拶や返事が届くと、", greetingReadyAfter: "{差出人アドレス}からお知らせをお送りします。メールの冒頭で、プロジェクトからのあいさつであることと、お送りした理由をご説明します。本文は手紙の画面で開きます。", greetingPending: "あいさつの配達が始まりましたら、送信の準備が整いしだいお知らせします。", greetingAction: "届いた挨拶を見る／次の挨拶を残す", greetingClosed: "あいさつの座標は、運営の準備が整いしだい、ここから始まります。",
  },
  "zh-Hans": {
    brand: "〈39岁以上〉· 参与记录", title: "我们保存您的记录", lead: "我们会持续关注这里留下的记忆与当下的故事。", print: "打印或保存为 PDF", retry: "再次确认保存", restart: "由另一个人重新开始", referral: "把项目告诉下一位参与者",
    status: { confirmed: "您的记录已作为研究资料保存。", sending: "正在将您的参与记录保存为研究资料。", unverified: "已发出保存请求，但尚未确认保存结果。记录副本仍保留在此设备上。", local_only: "参与记录已保存在此设备上。", failed: "记录还没有存到研究资料库。请点一下“再次确认保存”。" },
    audienceLead: "这份文档汇集了观众的记忆与判断、想再走近一次的心意，以及参与的条件。", otherLead: "这份文档会成为记录文化艺术当下的一份资料。",
    openCallBadge: "2026年12月 · Moho House", openCallTitle: "公开征集", openCallText: "我们正在等待 2026 年 12 月在 MOHO House 一同完成的作品。", openCallButton: "查看公开征集",
    greetingBrand: "问候的坐标", greetingTitle: "在不同记录之间留下问候", greetingStored: "参与者托付的问候会与问卷回答分开保存，并顺着64个坐标来策展。参与者之间不会公开姓名和电子邮箱。", greetingPreparing: "“问候的坐标”正在筹备，做法是顺着64个坐标，为一次相遇做策展。参与者之间不会公开姓名和电子邮箱。", greetingReason: "三个方向与64个坐标用于理解记录如何延续、变化并与哪些条件相遇，也用于说明为什么一则问候会抵达您。", greetingEmailLead: "如果希望收到问候，请留下电子邮箱。", greetingReadyBefore: "有新的问候或回复到达时，我们会通过 ", greetingReadyAfter: " 这个名字会用来发送通知。邮件开头会说明这是项目的问候，以及您为什么会收到它；信息本身要在信件页面上打开。", greetingPending: "问候的传递开始之后，等发信账户与服务器的邮件队列接通，我们会发送通知。", greetingAction: "查看到达的问候或留下下一则问候", greetingClosed: "问候的坐标在运营条件确定之后，会从这里开始。",
  },
  "zh-Hant": {
    brand: "〈39歲以上〉· 參與記錄", title: "我們保存您的記錄", lead: "我們會持續關注這裡留下的記憶與當下的故事。", print: "列印或儲存為 PDF", retry: "再次確認儲存", restart: "由另一個人重新開始", referral: "把專案告訴下一位參與者",
    status: { confirmed: "您的記錄已作為研究資料儲存。", sending: "正在將您的參與記錄儲存為研究資料。", unverified: "已送出儲存請求，但尚未確認儲存結果。記錄副本仍保留在此裝置上。", local_only: "參與記錄已儲存在此裝置上。", failed: "記錄還沒有存到研究資料庫。請點一下「再次確認儲存」。" },
    audienceLead: "這份文件匯集了觀眾的記憶與判斷、想再走近一次的心意，以及參與的條件。", otherLead: "這份文件會成為記錄文化藝術當下的一份資料。",
    openCallBadge: "2026年12月 · Moho House", openCallTitle: "公開徵件", openCallText: "我們正在等待 2026 年 12 月在 MOHO House 一同完成的作品。", openCallButton: "查看公開徵件",
    greetingBrand: "問候的座標", greetingTitle: "在不同記錄之間留下問候", greetingStored: "參與者託付的問候會與問卷回答分開保存，並順著64個座標來策展。參與者之間不會公開姓名和電子信箱。", greetingPreparing: "「問候的座標」正在籌備，做法是順著64個座標，為一次相遇做策展。參與者之間不會公開姓名和電子信箱。", greetingReason: "三個方向與64個座標用於理解記錄如何延續、變化並與哪些條件相遇，也用於說明為什麼一則問候會抵達您。", greetingEmailLead: "如果希望收到問候，請留下電子信箱。", greetingReadyBefore: "有新的問候或回覆到達時，我們會透過 ", greetingReadyAfter: " 這個名字會用來發送通知。郵件開頭會說明這是專案的問候，以及您為什麼會收到它；訊息本身要在信件頁面上開啟。", greetingPending: "問候的傳遞開始之後，等寄信帳號與伺服器的郵件佇列接通，我們會發送通知。", greetingAction: "查看到達的問候或留下下一則問候", greetingClosed: "問候的座標在營運條件確定之後，會從這裡開始。",
  },
  fr: {
    brand: "〈39 ans et plus〉 · RÉCIT DE PARTICIPATION", title: "Nous gardons votre récit", lead: "Nous prendrons le temps de regarder longuement les souvenirs et les récits d’aujourd’hui réunis ici.", print: "Imprimer ou enregistrer en PDF", retry: "Vérifier à nouveau l’enregistrement", restart: "Recommencer pour une autre personne", referral: "Parler du projet à la prochaine personne participante",
    status: { confirmed: "Votre récit a été enregistré comme document de recherche.", sending: "Votre récit de participation est en cours d’enregistrement comme document de recherche.", unverified: "Nous avons envoyé la demande, mais l’enregistrement n’est pas encore confirmé. Une copie du récit reste sur cet appareil.", local_only: "Le récit de participation est enregistré sur cet appareil.", failed: "Le récit n’est pas encore enregistré dans l’archive de recherche. Appuyez sur « Vérifier à nouveau l’enregistrement »." },
    audienceLead: "Ce document réunit les souvenirs et les appréciations d’une personne du public, l’envie de revenir, et les conditions qui rendent la participation possible.", otherLead: "Ce document rejoint un ensemble qui enregistre le présent des arts et de la culture.",
    openCallBadge: "Décembre 2026 · Moho House", openCallTitle: "Appel ouvert", openCallText: "Décembre 2026 · Nous attendons des travaux à mener ensemble à Moho House.", openCallButton: "Voir l’appel",
    greetingBrand: "Coordonnées de salutation", greetingTitle: "Laisser une salutation entre des récits différents", greetingStored: "Le message confié par une personne participante est conservé à part des réponses au questionnaire, puis apparié avec soin en suivant les soixante-quatre positions. Les noms et les adresses e-mail ne sont jamais partagés entre participants.", greetingPreparing: "« Les coordonnées d’un message » : nous le préparons de façon à composer une seule rencontre en suivant les soixante-quatre positions. Les noms et les adresses e-mail ne sont jamais partagés entre participants.", greetingReason: "Les trois directions et les soixante-quatre positions aident à lire comment votre récit se poursuit, où il change et quelles conditions il rencontre — et elles expliquent pourquoi tel message vous est parvenu.", greetingEmailLead: "Laissez une adresse e-mail si vous souhaitez recevoir un message.", greetingReadyBefore: "Si une nouvelle salutation ou une réponse arrive, nous enverrons une notification depuis ", greetingReadyAfter: ". Le début de l’e-mail explique qu’il s’agit d’une salutation du projet et pourquoi elle vous est destinée ; le message s’ouvre sur une page de lettre.", greetingPending: "Quand la remise des messages commencera, nous vous préviendrons.", greetingAction: "Voir une salutation arrivée ou en laisser une", greetingClosed: "« Les coordonnées d’un message » commenceront ici dès que tout sera prêt.",
  },
  es: {
    brand: "〈Mayores de 39〉 · REGISTRO DE PARTICIPACIÓN", title: "Guardamos su registro", lead: "Miraremos durante mucho tiempo los recuerdos y las historias del presente que quedan escritos aquí.", print: "Imprimir o guardar como PDF", retry: "Volver a comprobar el guardado", restart: "Empezar de nuevo para otra persona", referral: "Contar el proyecto a la próxima persona participante",
    status: { confirmed: "Su registro se ha guardado como material de investigación.", sending: "Estamos guardando su registro de participación como material de investigación.", unverified: "Hemos pedido que se guarde, pero todavía no hemos podido confirmar si se ha guardado. En este dispositivo queda una copia del registro.", local_only: "El registro de participación está guardado en este dispositivo.", failed: "El registro todavía no se ha guardado en el archivo de la investigación. Pulse «Volver a comprobar el guardado»." },
    audienceLead: "En este documento se han reunido los recuerdos y las valoraciones del público, las ganas de volver y las condiciones para participar.", otherLead: "Este documento pasa a formar parte de un registro del presente en las artes y la cultura.",
    openCallBadge: "Diciembre de 2026 · Moho House", openCallTitle: "Convocatoria", openCallText: "Diciembre de 2026 · Esperamos obras para compartir en Moho House.", openCallButton: "Ver convocatoria",
    greetingBrand: "Coordenadas de un saludo", greetingTitle: "Deje un saludo entre registros diferentes", greetingStored: "El saludo que confía una persona participante se guarda aparte de las respuestas de la encuesta y se empareja con criterio a lo largo de 64 coordenadas. Los nombres y las direcciones de correo no se comparten nunca entre participantes.", greetingPreparing: "Las Coordenadas de un saludo se están preparando como una forma de emparejar con criterio un único encuentro a lo largo de 64 coordenadas. Los nombres y las direcciones de correo no se comparten nunca entre participantes.", greetingReason: "Las tres direcciones y las 64 coordenadas se usan para leer cómo ha continuado y cómo ha cambiado un registro, con qué condiciones se encuentra, y para explicar por qué un saludo concreto ha llegado hasta usted.", greetingEmailLead: "Deje una dirección de correo si desea recibir un saludo.", greetingReadyBefore: "Si llega un saludo o respuesta nuevos, enviaremos un aviso desde ", greetingReadyAfter: ". El inicio del correo explica que se trata de un saludo del proyecto y por qué lo recibe; el mensaje se abre en una página de carta.", greetingPending: "Cuando empiece la entrega de saludos, le enviaremos un aviso. Todavía estamos terminando de prepararla.", greetingAction: "Ver un saludo recibido o dejar uno", greetingClosed: "Las Coordenadas de un saludo empezarán aquí en cuanto todo esté listo.",
  },
  nl: {
    brand: "〈39 jaar en ouder〉 · PARTICIPATIEVERSLAG", title: "We bewaren uw participatieverslag", lead: "We zullen de herinneringen en de verhalen van nu die hier staan, lang blijven bekijken.", print: "Afdrukken of als PDF opslaan", retry: "Opslaan opnieuw controleren", restart: "Opnieuw beginnen voor iemand anders", referral: "Vertel de volgende deelnemer over het project",
    status: { confirmed: "Uw verslag is bewaard als onderzoeksmateriaal.", sending: "Uw participatieverslag wordt als onderzoeksmateriaal opgeslagen.", unverified: "We hebben het verzoek om op te slaan verstuurd, maar nog geen bevestiging terug. Een kopie van het verslag blijft op dit apparaat staan.", local_only: "Het participatieverslag is op dit apparaat opgeslagen.", failed: "Het verslag staat nog niet in het onderzoeksarchief. Klik op “Opslag opnieuw controleren”." },
    audienceLead: "In dit document staan de herinneringen en de afwegingen van iemand uit het publiek, de wens om terug te komen, en de voorwaarden om mee te kunnen doen.", otherLead: "Dit document wordt deel van een verslag van kunst en cultuur zoals die er nu bij staan.",
    openCallBadge: "December 2026 · Moho House", openCallTitle: "Open oproep", openCallText: "December 2026 · We wachten op werk om samen te maken bij Moho House.", openCallButton: "Bekijk de oproep",
    greetingBrand: "Coördinaten van een groet", greetingTitle: "Laat een groet achter tussen verschillende records", greetingStored: "De groet die een deelnemer toevertrouwt, bewaren we apart van de antwoorden op de vragenlijst en stellen we samen langs de vierenzestig coördinaten. Namen en e-mailadressen worden nooit tussen deelnemers gedeeld.", greetingPreparing: "«Coördinaten van een groet» bereiden we zo voor dat er langs de vierenzestig coördinaten één ontmoeting wordt samengesteld. Namen en e-mailadressen worden nooit tussen deelnemers gedeeld.", greetingReason: "De drie richtingen en de vierenzestig coördinaten helpen ons te lezen hoe uw verslag doorloopt, waar het verandert en welke voorwaarden het tegenkomt — en ze verklaren waarom juist die ene groet u bereikte.", greetingEmailLead: "Laat een e-mailadres achter als u een groet wilt ontvangen.", greetingReadyBefore: "Wanneer een nieuwe groet of antwoord aankomt, sturen we een bericht vanaf ", greetingReadyAfter: ". De opening van de e-mail legt uit dat het een projectgroet is en waarom u die ontvangt; het bericht opent op een briefpagina.", greetingPending: "Zodra we groeten gaan bezorgen, sturen we u bericht.", greetingAction: "Bekijk een aangekomen groet of laat er een achter", greetingClosed: "«Coördinaten van een groet» gaat hier van start zodra alles ervoor klaarstaat.",
  },
  ms: {
    brand: "〈39 tahun ke atas〉 · REKOD PENYERTAAN", title: "Kami menyimpan rekod anda", lead: "Kami akan lama meneliti ingatan dan cerita masa kini yang tertulis di sini.", print: "Cetak atau simpan sebagai PDF", retry: "Semak simpanan sekali lagi", restart: "Mula baharu untuk orang lain", referral: "Kongsikan projek dengan peserta seterusnya",
    status: { confirmed: "Rekod anda telah disimpan sebagai bahan penyelidikan.", sending: "Rekod penyertaan anda sedang disimpan sebagai bahan penyelidikan.", unverified: "Kami telah meminta agar rekod disimpan, tetapi kami masih belum dapat mengesahkan sama ada ia tersimpan. Satu salinan rekod kekal pada peranti ini.", local_only: "Rekod penyertaan disimpan pada peranti ini.", failed: "Rekod belum disimpan dalam arkib penyelidikan. Sila tekan “Semak semula penyimpanan”." },
    audienceLead: "Dalam dokumen ini terhimpun ingatan dan pertimbangan penonton, keinginan untuk kembali, dan keadaan untuk menyertainya.", otherLead: "Dokumen ini menjadi sebahagian daripada rekod tentang masa kini dalam seni dan budaya.",
    openCallBadge: "Disember 2026 · Moho House", openCallTitle: "Panggilan terbuka", openCallText: "Disember 2026 · Kami menantikan karya untuk dikongsi bersama di Moho House.", openCallButton: "Lihat panggilan",
    greetingBrand: "Koordinat salam", greetingTitle: "Tinggalkan salam antara rekod yang berbeza", greetingStored: "Salam yang diamanahkan oleh peserta disimpan berasingan daripada jawapan soal selidik, dan dikurasi mengikut 64 koordinat. Nama dan alamat e-mel tidak pernah dikongsi antara peserta.", greetingPreparing: "Koordinat salam sedang disediakan sebagai cara mengurasi satu pertemuan mengikut 64 koordinat. Nama dan alamat e-mel tidak pernah dikongsi antara peserta.", greetingReason: "Tiga arah dan 64 koordinat digunakan untuk membaca bagaimana sesuatu rekod itu berterusan dan berubah, keadaan apa yang ditemuinya, serta untuk menerangkan mengapa satu salam tertentu sampai kepada anda.", greetingEmailLead: "Tinggalkan alamat e-mel jika anda ingin menerima salam.", greetingReadyBefore: "Jika salam atau balasan baharu tiba, kami akan menghantar pemberitahuan daripada ", greetingReadyAfter: ". Pembukaan e-mel menerangkan bahawa ini ialah salam projek dan mengapa anda menerimanya; mesej itu dibuka pada halaman surat.", greetingPending: "Apabila penghantaran salam bermula, kami akan menghantar pemberitahuan kepada anda. Kami masih menyiapkan persediaannya.", greetingAction: "Lihat salam yang telah tiba atau tinggalkan satu", greetingClosed: "Koordinat salam akan bermula di sini sebaik sahaja semuanya siap.",
  },
};

export function completionCopy(language = "ko") {
  return copy[language] || copy.en;
}
