import { withHongKong } from "./hong-kong.js?v=v7-20261003-r107";
// Completion is a participant-facing service screen. Keep it separate from
// the response-document frame so a record can remain in its source language
// while this surrounding interface follows the selected interface language.
const copy = {
  ko: {
    brand: "〈만 39세 이상〉 · 참여 기록", title: "당신의 기록을 남깁니다", lead: "여기 적힌 기억과 지금의 이야기를 오래 살펴보겠습니다.", print: "인쇄·PDF 저장", retry: "저장 다시 확인", restart: "이 기기에서 다른 분이 참여하기", referral: "다음 참여자에게 프로젝트 전하기",
    status: { confirmed: "당신의 기록을 연구 자료로 저장했어요.", sending: "참여 기록을 연구 자료로 저장하고 있어요.", unverified: "저장을 요청했지만, 저장 여부는 아직 확인하지 못했습니다. 기록 사본은 이 기기에 남아 있습니다.", local_only: "참여 기록을 이 기기에 저장했습니다.", failed: "아직 연구 저장소에 저장되지 않았습니다. 「저장 다시 확인」을 눌러주세요." },
    audienceLead: "이 문서에는 관객의 기억과 판단, 다시 찾고 싶은 마음과 참여 조건이 함께 담겼어요.", otherLead: "이 문서는 문화예술의 현재를 기록하는 자료로 이어집니다.",
    openCallBadge: "2026년 12월 · 모호주택", openCallTitle: "공모", openCallText: "2026년 12월 · 모호주택에서 함께할 작업을 기다립니다.", openCallButton: "공모 보기",
    greetingBrand: "안부의 좌표", greetingTitle: "서로 다른 기록 사이에 안부를 남깁니다", greetingStored: "참여자가 맡긴 안부는 설문 응답과 분리해 보관하고 64개의 좌표를 따라 큐레이션합니다. 이름과 이메일은 서로에게 공개하지 않습니다.", greetingPreparing: "안부의 좌표는 64개의 좌표를 따라 한 번의 만남을 큐레이션하는 방식으로 준비하고 있습니다. 이름과 이메일은 서로에게 공개하지 않습니다.", greetingReason: "세 방향과 64개의 좌표는 기록이 어떻게 이어지고 달라졌는지, 어떤 조건과 만나는지를 읽고 왜 한 안부가 당신에게 닿았는지 설명하는 데 사용합니다.", greetingEmailLead: "안부를 받고 싶다면 이메일을 남겨주세요.", greetingReadyBefore: "새 안부나 답장이 도착하면 ", greetingReadyAfter: " 이름으로 알림을 보냅니다. 메일 첫 문단에서 프로젝트 안부라는 점과 수신 이유를 설명하고, 메시지는 편지 화면에서 열어봅니다.", greetingPending: "안부 전달이 시작되면 발신 계정과 서버 메일 큐가 연결된 뒤 알림을 보냅니다.", greetingAction: "도착한 안부 보고 다음 안부 남기기", greetingClosed: "안부의 좌표 운영 조건이 확정되면 이곳에서 시작합니다.",
  },
  en: {
    brand: "〈Over 39〉 · PARTICIPATION RECORD", title: "We keep your record", lead: "We will spend a long time with the memories and stories of the present written here.", print: "Print or save as PDF", retry: "Check the save again", restart: "Let someone else take part on this device", referral: "Share the project with the next participant",
    status: { confirmed: "Your record has been saved as research material.", sending: "Saving your participation record as research material.", unverified: "We have asked for your record to be saved, but cannot confirm yet that it was. A copy of the record remains on this device.", local_only: "Your participation record has been saved on this device.", failed: "Your record has not been saved to the research archive yet. Please press “Check the save again”." },
    audienceLead: "This document holds an audience member’s memories and judgements, the wish to go back, and the conditions for taking part.", otherLead: "This document becomes part of a record of arts and culture as they are now.",
    openCallBadge: "December 2026 · Moho House", openCallTitle: "Open call", openCallText: "December 2026 · We are inviting work to join us at Moho House.", openCallButton: "View open call",
    greetingBrand: "Coordinates of Greeting", greetingTitle: "Leaving greetings between different records", greetingStored: "Greetings that participants leave with us are kept separately from survey responses and curated along the 64 coordinates. Names and email addresses are not shared between participants.", greetingPreparing: "Coordinates of Greeting is being prepared as a way of curating a single encounter along the 64 coordinates. Names and email addresses are not shared between participants.", greetingReason: "The three directions and the 64 coordinates are used to read how a record has carried on and changed and what conditions it meets, and to explain why a particular greeting reached you.", greetingEmailLead: "If you would like to receive a greeting, please leave your email address.", greetingReadyBefore: "When a new greeting or reply arrives, we will send you a notice from ", greetingReadyAfter: ". The first paragraph of the email explains that it is a greeting from the project and why you are receiving it; the message itself opens on a letter page.", greetingPending: "Once greetings start being delivered, we will send notices after the sending account and the server’s mail queue are connected.", greetingAction: "Read the greeting that has arrived, then leave the next one", greetingClosed: "Coordinates of Greeting will start here once the arrangements for running it are settled.",
  },
  ja: {
    brand: "〈39歳以上〉・参加記録", title: "あなたの記録を残します", lead: "ここに書かれた記憶といまのお話を、長い時間をかけて読んでいきます。", print: "印刷・PDF保存", retry: "保存をもう一度確認", restart: "この端末で別の方が参加する", referral: "次の参加者にプロジェクトを伝える",
    status: { confirmed: "記録を研究資料として保存しました。", sending: "参加記録を研究資料として保存しています。", unverified: "保存を依頼しましたが、保存できたかどうかはまだ確認できていません。記録の控えは、この端末に残っています。", local_only: "参加記録をこの端末に保存しました。", failed: "研究用の保管先には、まだ保存されていません。「保存をもう一度確認」を押してください。" },
    audienceLead: "この文書には、観客としての記憶と判断、もう一度訪れたい気持ち、参加を支える条件がともに収められています。", otherLead: "この文書は、文化芸術の今を記録する資料の一つになります。",
    openCallBadge: "2026年12月・モホハウス", openCallTitle: "公募", openCallText: "2026年12月・モホハウスで、ともにつくる作品をお待ちしています。", openCallButton: "公募を見る",
    greetingBrand: "あいさつの座標", greetingTitle: "異なる記録のあいだにあいさつを残します", greetingStored: "参加者から預かったあいさつは調査の回答とは分けて保管し、64の座標をたどってお届けする相手を選びます。名前とメールアドレスが参加者どうしに公開されることはありません。", greetingPreparing: "あいさつの座標は、64の座標をたどって一度の出会いを選ぶしくみとして準備中です。名前とメールアドレスが参加者どうしに公開されることはありません。", greetingReason: "三つの方向と64の座標は、記録がどのように続き、どう変わったのか、どの条件と出会うのかを読み、なぜこのあいさつがあなたに届いたのかを説明するために使います。", greetingEmailLead: "あいさつを受け取りたい方は、メールアドレスをご記入ください。", greetingReadyBefore: "新しいあいさつや返事が届くと、", greetingReadyAfter: "の名前でお知らせをお送りします。メールの冒頭で、プロジェクトからのあいさつであることと、お送りした理由をご説明します。本文は手紙の画面で開きます。", greetingPending: "あいさつの配達が始まりましたら、送信の準備が整いしだいお知らせします。", greetingAction: "届いたあいさつを読んで、次のあいさつを残す", greetingClosed: "あいさつの座標は、運営の準備が整いしだい、ここから始まります。",
  },
  "zh-Hans": {
    brand: "〈39岁以上〉· 参与记录", title: "我们为您留存这份记录", lead: "这里写下的记忆和当下的故事，我们会长久地细细阅读。", print: "打印或保存为 PDF", retry: "再次确认保存", restart: "换一个人用这台设备参与", referral: "把这个项目分享给下一位参与者",
    status: { confirmed: "您的记录已作为研究资料保存。", sending: "正在将您的参与记录保存为研究资料。", unverified: "已发出保存请求，但还没能确认是否保存成功。记录的副本仍留在这台设备上。", local_only: "参与记录已保存在这台设备上。", failed: "记录还没有存到研究资料库。请点一下“再次确认保存”。" },
    audienceLead: "这份文件里，有观众的记忆与判断、想再去看看的心情，以及参与的条件。", otherLead: "这份文件会成为记录文化艺术当下的一份资料。",
    openCallBadge: "2026年12月 · Moho House", openCallTitle: "公开征集", openCallText: "我们在等待2026年12月于 Moho House 一起完成的作品。", openCallButton: "查看公开征集",
    greetingBrand: "问候坐标", greetingTitle: "在不同的记录之间，留下问候", greetingStored: "参与者交给我们的问候，会与问卷回答分开保管，并按照64个坐标来策展。参与者之间不会互相公开姓名和邮箱。", greetingPreparing: "“问候坐标”正在筹备中，做法是依照64个坐标，以策展的方式安排一次相遇。参与者之间不会互相公开姓名和邮箱。", greetingReason: "三个方向和64个坐标，用来读出记录如何延续、如何变化、与哪些条件相遇，也用来说明某一封问候为什么会到达您这里。", greetingEmailLead: "如果想收到问候，请留下邮箱。", greetingReadyBefore: "有新的问候或回信到达时，我们会以 ", greetingReadyAfter: " 的名义发送通知。邮件第一段会说明这是项目的问候，以及您为什么会收到；正文要到信件页面上打开阅读。", greetingPending: "问候的传递开始之后，等发信账户与服务器的邮件队列接通，我们会发送通知。", greetingAction: "读到达的问候，再留下一封给下一位", greetingClosed: "等“问候坐标”的运营条件确定后，会从这里开始。",
  },
  "zh-Hant": {
    brand: "〈39歲以上〉· 參與記錄", title: "我們保存您的記錄", lead: "這裡寫下的記憶與現在的故事，我們會長久地細細閱讀。", print: "列印或儲存為 PDF", retry: "再次確認儲存", restart: "讓其他人在本裝置上參與", referral: "把這個計畫傳給下一位參與者",
    status: { confirmed: "您的記錄已作為研究資料儲存。", sending: "正在將您的參與記錄儲存為研究資料。", unverified: "已送出儲存請求，但還無法確認是否儲存成功。記錄副本仍保留在這台裝置上。", local_only: "參與記錄已儲存在這台裝置上。", failed: "記錄還沒有存到研究資料庫。請點一下「再次確認儲存」。" },
    audienceLead: "這份文件收錄了觀眾的記憶與判斷、想再去看看的心情，以及參與的條件。", otherLead: "這份文件會成為記錄文化藝術現況的一份資料。",
    openCallBadge: "2026年12月 · Moho House", openCallTitle: "公開徵件", openCallText: "我們正在等待 2026 年 12 月能在 Moho House 一同參與的作品。", openCallButton: "查看公開徵件",
    greetingBrand: "問候的座標", greetingTitle: "在不同記錄之間留下問候", greetingStored: "參與者託付的問候，會和問卷回答分開保存，並依照64個座標來策展。參與者之間不會公開彼此的姓名和電子信箱。", greetingPreparing: "「問候的座標」正在籌備中，將依照64個座標，為一場相遇進行策展。參與者之間不會公開彼此的姓名和電子信箱。", greetingReason: "三個方向與64個座標，是用來解讀記錄如何延續、如何改變、又和哪些條件相遇，並說明為什麼某一則問候會送到您這裡。", greetingEmailLead: "如果希望收到問候，請留下電子信箱。", greetingReadyBefore: "有新的問候或回信寄到時，我們會透過 ", greetingReadyAfter: " 這個名稱寄出通知。郵件第一段會說明這是本計畫的問候，以及您收到它的原因；訊息內容則在信件頁面上開啟閱讀。", greetingPending: "問候的傳遞開始之後，等寄信帳號與伺服器的郵件佇列接通，我們會發送通知。", greetingAction: "看完寄來的問候，再留下下一則", greetingClosed: "「問候的座標」的運作條件確定後，就會從這裡開始。",
  },
  fr: {
    brand: "〈39 ans et plus〉 · RÉCIT DE PARTICIPATION", title: "Nous gardons votre récit", lead: "Nous prendrons le temps de regarder longuement les souvenirs et les récits d’aujourd’hui réunis ici.", print: "Imprimer ou enregistrer en PDF", retry: "Revérifier l’enregistrement", restart: "Passer l’appareil à une autre personne", referral: "Faire découvrir le projet à d’autres participant·es",
    status: { confirmed: "Votre récit est enregistré comme matériau de recherche.", sending: "Votre récit de participation est en cours d’enregistrement comme matériau de recherche.", unverified: "L’enregistrement a été demandé, mais nous n’avons pas encore pu vérifier qu’il a abouti. Une copie de votre récit reste sur cet appareil.", local_only: "Le récit de participation est enregistré sur cet appareil.", failed: "Votre récit n’est pas encore enregistré dans l’archive de la recherche. Appuyez sur « Revérifier l’enregistrement »." },
    audienceLead: "Ce document réunit les souvenirs et les appréciations d’une personne du public, l’envie de revenir, et les conditions qui rendent la participation possible.", otherLead: "Ce document rejoint les archives du présent des arts et de la culture.",
    openCallBadge: "Décembre 2026 · Moho House", openCallTitle: "Appel à projets", openCallText: "Décembre 2026 · Nous attendons des projets à mener ensemble à Moho House.", openCallButton: "Voir l’appel",
    greetingBrand: "La carte des messages", greetingTitle: "Un message laissé d’un récit à l’autre", greetingStored: "Les messages confiés par les personnes participantes sont conservés à part des réponses au questionnaire, puis mis en relation avec soin selon les soixante-quatre positions. Les noms et les adresses e-mail ne sont pas communiqués entre personnes participantes.", greetingPreparing: "Nous préparons « La carte des messages » : une façon de composer avec soin, selon les soixante-quatre positions, une rencontre qui n’a lieu qu’une fois. Les noms et les adresses e-mail ne sont pas communiqués entre personnes participantes.", greetingReason: "Les trois directions et les soixante-quatre positions servent à lire comment votre récit se poursuit et change, et quelles conditions il rencontre ; elles servent aussi à expliquer pourquoi tel message vous est parvenu.", greetingEmailLead: "Laissez une adresse e-mail si vous souhaitez recevoir un message.", greetingReadyBefore: "Si un nouveau message ou une réponse vous parvient, vous recevrez une notification de la part de ", greetingReadyAfter: ". Dès le premier paragraphe, l’e-mail précise qu’il s’agit d’un message du projet et pourquoi vous le recevez ; le message lui-même s’ouvre dans une page en forme de lettre.", greetingPending: "Lorsque la remise des messages commencera, nous vous enverrons une notification, une fois l’envoi des e-mails mis en place.", greetingAction: "Lire le message reçu, puis en laisser un à votre tour", greetingClosed: "« La carte des messages » ouvrira ici dès que ses conditions de fonctionnement seront arrêtées.",
  },
  es: {
    brand: "〈39 y más〉 · REGISTRO DE PARTICIPACIÓN", title: "Guardamos su registro", lead: "Leeremos con atención, y durante mucho tiempo, los recuerdos y las historias del presente que quedan escritos aquí.", print: "Imprimir o guardar como PDF", retry: "Comprobar de nuevo si se guardó", restart: "Que otra persona participe en este dispositivo", referral: "Compartir el proyecto con la próxima persona participante",
    status: { confirmed: "Hemos guardado su registro como material de investigación.", sending: "Estamos guardando su registro de participación como material de investigación.", unverified: "Hemos pedido que se guarde, pero todavía no hemos podido confirmar si se ha guardado. En este dispositivo queda una copia del registro.", local_only: "El registro de participación está guardado en este dispositivo.", failed: "Su registro todavía no se ha guardado en el archivo de la investigación. Pulse «Comprobar de nuevo si se guardó»." },
    audienceLead: "Este documento reúne sus recuerdos y valoraciones como público, sus ganas de volver y las condiciones para participar.", otherLead: "Este documento pasa a formar parte de un registro del presente en las artes y la cultura.",
    openCallBadge: "Diciembre de 2026 · Moho House", openCallTitle: "Convocatoria", openCallText: "Diciembre de 2026 · Esperamos obras para compartir en Moho House.", openCallButton: "Ver convocatoria",
    greetingBrand: "Coordenadas de un saludo", greetingTitle: "Un saludo entre registros distintos", greetingStored: "El saludo que confía cada participante se guarda aparte de las respuestas de la encuesta y se selecciona con criterio curatorial siguiendo las 64 coordenadas. Los nombres y los correos electrónicos no se revelan entre participantes.", greetingPreparing: "Las Coordenadas de un saludo se están preparando como una forma de organizar, con criterio curatorial, un único encuentro siguiendo las 64 coordenadas. Los nombres y los correos electrónicos no se revelan entre participantes.", greetingReason: "Las tres direcciones y las 64 coordenadas sirven para leer cómo ha seguido y cómo ha cambiado un registro y con qué condiciones se cruza, y para explicar por qué un saludo ha llegado hasta usted.", greetingEmailLead: "Si desea recibir un saludo, deje su dirección de correo.", greetingReadyBefore: "Cuando llegue un saludo o una respuesta nuevos, le enviaremos un aviso desde ", greetingReadyAfter: ". En el primer párrafo del correo se explica que es un saludo del proyecto y por qué lo recibe; el mensaje se abre en una página de carta.", greetingPending: "Cuando empiece la entrega de saludos, le enviaremos un aviso en cuanto esté conectado el correo de envío.", greetingAction: "Ver el saludo recibido y dejar el siguiente", greetingClosed: "Las Coordenadas de un saludo empezarán aquí cuando se definan sus condiciones de funcionamiento.",
  },
  nl: {
    brand: "〈39 jaar en ouder〉 · Deelnameverslag", title: "We bewaren uw verslag", lead: "We zullen lang en aandachtig lezen wat hier staat: uw herinneringen en uw verhaal van nu.", print: "Afdrukken of als PDF opslaan", retry: "Opslag opnieuw controleren", restart: "Iemand anders laten meedoen op dit apparaat", referral: "Het project aan een volgende deelnemer doorvertellen",
    status: { confirmed: "Uw verslag is opgeslagen als onderzoeksmateriaal.", sending: "Uw deelnameverslag wordt opgeslagen als onderzoeksmateriaal.", unverified: "We hebben gevraagd om het op te slaan, maar weten nog niet zeker of dat gelukt is. Een kopie van het verslag staat nog op dit apparaat.", local_only: "Uw deelnameverslag is op dit apparaat opgeslagen.", failed: "Het verslag is nog niet opgeslagen in het onderzoeksarchief. Klik op ‘Opslag opnieuw controleren’." },
    audienceLead: "In dit document staan de herinneringen en de afwegingen van iemand uit het publiek, de wens om terug te komen, en de voorwaarden om mee te kunnen doen.", otherLead: "Dit document wordt deel van het materiaal dat vastlegt hoe kunst en cultuur er nu voor staan.",
    openCallBadge: "December 2026 · Moho House", openCallTitle: "Open oproep", openCallText: "December 2026 · We wachten op werk dat we samen bij Moho House kunnen laten zien.", openCallButton: "Bekijk de oproep",
    greetingBrand: "Groetcoördinaten", greetingTitle: "Een groet achterlaten tussen verschillende verslagen", greetingStored: "Groeten die deelnemers toevertrouwen, bewaren we apart van de antwoorden op de vragenlijst; we cureren ze aan de hand van de vierenzestig coördinaten. Namen en e-mailadressen worden niet onderling gedeeld.", greetingPreparing: "‘Groetcoördinaten’ bereiden we voor als één gecureerde ontmoeting, aan de hand van de vierenzestig coördinaten. Namen en e-mailadressen worden niet onderling gedeeld.", greetingReason: "De drie richtingen en de vierenzestig coördinaten gebruiken we om te lezen hoe een verslag doorliep en veranderde en welke voorwaarden het tegenkwam, en om uit te leggen waarom een bepaalde groet bij u terechtkwam.", greetingEmailLead: "Wilt u een groet ontvangen? Laat dan uw e-mailadres achter.", greetingReadyBefore: "Komt er een nieuwe groet of een antwoord aan, dan sturen we u een melding vanaf ", greetingReadyAfter: ". In de eerste alinea van de e-mail leest u dat het om een groet van het project gaat en waarom u deze mail krijgt; het bericht zelf opent u op een briefpagina.", greetingPending: "Zodra we groeten gaan bezorgen en het verzendadres en de mailwachtrij zijn gekoppeld, sturen we u bericht.", greetingAction: "De aangekomen groet lezen en de volgende achterlaten", greetingClosed: "‘Groetcoördinaten’ begint hier zodra vaststaat hoe het zal werken.",
  },
  ms: {
    brand: "〈39 tahun ke atas〉 · REKOD PENYERTAAN", title: "Kami menyimpan rekod anda", lead: "Kami akan lama meneliti ingatan dan cerita masa kini yang tertulis di sini.", print: "Cetak atau simpan sebagai PDF", retry: "Semak semula penyimpanan", restart: "Biarkan orang lain menyertai pada peranti ini", referral: "Kongsikan projek dengan peserta seterusnya",
    status: { confirmed: "Rekod anda telah disimpan sebagai bahan penyelidikan.", sending: "Rekod penyertaan anda sedang disimpan sebagai bahan penyelidikan.", unverified: "Kami telah meminta agar rekod disimpan, tetapi kami masih belum dapat mengesahkan sama ada ia tersimpan. Satu salinan rekod kekal pada peranti ini.", local_only: "Rekod penyertaan telah disimpan pada peranti ini.", failed: "Rekod belum disimpan dalam arkib penyelidikan. Sila tekan “Semak semula penyimpanan”." },
    audienceLead: "Dokumen ini menghimpunkan ingatan dan pertimbangan penonton, keinginan untuk kembali mencari, dan keadaan untuk menyertai.", otherLead: "Dokumen ini menjadi sebahagian daripada bahan yang merekodkan masa kini seni dan budaya.",
    openCallBadge: "Disember 2026 · Moho House", openCallTitle: "Panggilan terbuka", openCallText: "Disember 2026 · Kami menantikan karya untuk dikongsi bersama di Moho House.", openCallButton: "Lihat panggilan",
    greetingBrand: "Koordinat Salam", greetingTitle: "Meninggalkan salam di antara rekod yang berbeza", greetingStored: "Salam yang diamanahkan oleh peserta disimpan berasingan daripada jawapan soal selidik dan dikurasi mengikut 64 koordinat. Nama dan e-mel tidak didedahkan antara peserta.", greetingPreparing: "Koordinat Salam sedang disediakan sebagai cara mengurasi satu pertemuan mengikut 64 koordinat. Nama dan e-mel tidak didedahkan antara peserta.", greetingReason: "Tiga arah dan 64 koordinat digunakan untuk membaca bagaimana rekod berterusan dan berubah serta keadaan yang ditemuinya, dan untuk menerangkan mengapa satu salam sampai kepada anda.", greetingEmailLead: "Jika anda ingin menerima salam, sila tinggalkan alamat e-mel anda.", greetingReadyBefore: "Jika salam atau balasan baharu tiba, kami akan menghantar pemberitahuan atas nama ", greetingReadyAfter: ". Perenggan pertama e-mel itu menerangkan bahawa ia salam daripada projek ini dan sebab anda menerimanya. Mesejnya pula dibuka di halaman surat.", greetingPending: "Apabila penghantaran salam bermula, kami akan menghantar pemberitahuan selepas akaun penghantar dan sistem e-mel kami disambungkan.", greetingAction: "Baca salam yang sudah tiba dan tinggalkan salam seterusnya", greetingClosed: "Koordinat Salam akan bermula di sini apabila syarat pengendaliannya dimuktamadkan.",
  },
};

export function completionCopy(language = "ko") {
  return copy[language] || copy.en;
}

// 홍콩판(zh-Hant-HK)은 번체에서 만든다 — hong-kong.js(2026-10-01).
[copy].forEach(withHongKong);
