export const QUESTION_METADATA = {
  P05: { purpose: "활동 또는 관람 경험의 시간 범위", axis: "S", evidence: "support", intent: "응답이 놓인 시간의 폭을 이해하기 위한 질문입니다." },
  P06: { purpose: "현재 활동 또는 관람 방식", axis: "S", evidence: "support", intent: "활동하거나 문화예술을 찾아보는 방식이 어떤 리듬으로 이어지는지 살핍니다." },
  P07: { purpose: "관심·활동과 실제 참여의 관계", axis: "S", evidence: "support", intent: "평소 이어지는 관심과 현장에 드러난 활동·참여의 관계를 함께 봅니다." },
  P14: { purpose: "작품 제작 또는 핵심 활동의 현재 상태", axis: "S", evidence: "support", intent: "작품 제작과 외부 공개를 나누어 현재 상태를 기록합니다." },
  P15: { purpose: "전시·발표·공개 참여의 현재 상태", axis: "S", evidence: "support", intent: "작품 제작과 공개 발표가 서로 다르게 이어질 수 있음을 기록합니다." },
  P16: { purpose: "작품·전시·참여가 쉬거나 달라진 이유", axis: "S", evidence: "context", intent: "현재 상태에 함께 작용한 생활, 창작, 관계와 현장의 조건을 살핍니다." },
  P17: { purpose: "현재의 관계 상태에 대한 참여자의 판단", axis: "S", evidence: "primary", intent: "현재의 관계를 확장·지속·전환·거리와 한계의 흐름으로 읽기 위한 직접 단서로 사용합니다." },
  P18: { purpose: "현재 상태가 시작된 시기와 장면", axis: "S", evidence: "primary", intent: "현재 상태가 형성된 시기와 실제로 작용한 일을 참여자의 말로 기록합니다." },
  P19: { purpose: "활동·관람·기억을 지지해 온 조건", axis: "S", evidence: "support", intent: "실제로 이어지게 한 사람, 공간, 생활 기반, 정보와 기록의 조건을 살핍니다." },
  P19_TEXT: { purpose: "지지 조건이 작동한 실제 장면", axis: "S", evidence: "primary", intent: "선택한 조건이 삶과 활동에서 어떻게 작동했는지 참여자의 말로 기록합니다." },
  P11: { purpose: "전환 시점", axis: "S", evidence: "context", intent: "연령, 지원, 역할 또는 참여 방식이 달라진 시점을 살핍니다." },
  P12: { purpose: "전환의 구체적 장면", axis: "S", evidence: "primary", intent: "그 전후로 실제로 달라진 경험을 참여자의 말로 기록합니다." },
  P13: { purpose: "공개된 자리 밖의 지속", axis: "S", evidence: "support", intent: "발표·관람·프로그램 밖에서도 이어진 작업, 관심, 기억과 관계를 확인합니다." },
  P13_TEXT: { purpose: "비가시적 지속 원문", axis: "S", evidence: "primary", intent: "이어짐, 멈춤, 거리두기 또는 휴식의 실제 모습을 참여자의 말로 남깁니다." },
  M01: { purpose: "기억 또는 활동의 출발점", axis: "M", evidence: "context", intent: "오늘 이야기를 시작할 사람, 작업, 공간, 장면 또는 감각을 고릅니다." },
  NO_RECALL_RELATION: { purpose: "현재 문화예술 관계의 장면", axis: "S", evidence: "primary", intent: "특정 기억을 요구하지 않고 현재 문화예술과 가까워지거나 멀어지는 생활의 장면을 기록합니다." },
  M02: { purpose: "남아 있는 장면 원문", axis: "M", evidence: "primary", intent: "정확한 이름보다 먼저 남아 있는 장면과 표현을 기록합니다." },
  M03: { purpose: "대상별 기억의 초점", axis: "M", evidence: "support", intent: "선택한 대상에서 무엇이 먼저 떠오르는지 살핍니다." },
  M04: { purpose: "기억의 주된 의미 자기확인", axis: "M", evidence: "support", intent: "자신의 문장을 남긴 뒤 가까운 의미의 방향을 확인합니다." },
  M04_TEXT: { purpose: "기억의 의미 원문", axis: "M", evidence: "primary", intent: "그 기억이 오래 남은 이유를 참여자의 언어로 먼저 듣습니다." },
  M05: { purpose: "기억 의미의 보조 근거", axis: "M", evidence: "support", intent: "주된 의미와 함께 남아 있는 다른 단서를 살핍니다." },
  M06: { purpose: "기억 시기", axis: "M", evidence: "context", intent: "기억이 놓인 시간대를 기록합니다." },
  M07: { purpose: "기억 지역", axis: "M", evidence: "context", intent: "기억이 생긴 장소와 이동의 맥락을 기록합니다." },
  M08: { purpose: "경험 방식", axis: "M", evidence: "support", intent: "직접 경험과 기록을 통한 경험을 구분해 봅니다." },
  M09: { purpose: "기억 대상과의 관계", axis: "M", evidence: "support", intent: "이 기억을 바라보는 관계의 위치를 확인합니다." },
  M10: { purpose: "다음 증언자", axis: "M", evidence: "context", intent: "기억을 더 이어 줄 수 있는 다른 시선을 찾습니다." },
  D01: { purpose: "현재 크게 체감하는 조건", axis: "D", evidence: "support", intent: "지금의 활동과 참여에서 크게 체감되는 조건을 확인합니다." },
  D02: { purpose: "가장 먼저 바라는 변화 자기확인", axis: "D", evidence: "support", intent: "자신의 문장을 남긴 뒤 변화의 방향을 확인합니다." },
  D02_TEXT: { purpose: "바라는 변화 원문", axis: "D", evidence: "primary", intent: "먼저 달라졌으면 하는 실제 장면을 참여자의 언어로 기록합니다." },
  D03: { purpose: "변화가 필요한 현실 맥락", axis: "D", evidence: "support", intent: "선택한 변화가 어떤 현실에서 비롯되는지 확인합니다." },
  D04: { purpose: "조건의 구체적 영향", axis: "D", evidence: "context", intent: "그 조건이 활동과 기억에 남긴 영향을 참여자의 말로 기록합니다." },
  R01: { purpose: "연구 이후 이어짐의 방식", axis: "D", evidence: "context", intent: "기억과 경험이 다음에 어떤 모습으로 이어지면 좋을지 살핍니다." },
  AI_MEMORY_OBJECT: { purpose: "기억 대상 확인", axis: "M", evidence: "context", intent: "사람, 작품, 전시, 공간, 장면 가운데 기억의 대상을 확인합니다." },
  AI_MEMORY_SCENE: { purpose: "장면 구체화", axis: "M", evidence: "primary", intent: "길거나 여러 갈래인 답변에서 선명한 한 장면을 더 듣습니다." },
  AI_MEMORY_REASON: { purpose: "기억과 현재의 연결", axis: "M", evidence: "primary", intent: "기억이 현재의 생각, 선택, 활동 또는 관람과 이어지는 지점을 듣습니다." },
  AI_PRESENT: { purpose: "현재와 전환의 미응답 맥락 탐색", axis: "S", evidence: "primary", intent: "현재의 움직임, 전환, 보이지 않는 지속 가운데 필요한 한 지점을 더 묻습니다." },
  AI_CONDITIONS: { purpose: "변화와 관계의 미응답 맥락 탐색", axis: "D", evidence: "primary", intent: "바라는 변화와 다음 관계에서 아직 열리지 않은 한 지점을 더 묻습니다." },
};

export const FIXED_RESEARCH_QUESTION_MAP = Object.entries(QUESTION_METADATA)
  .filter(([id]) => !id.startsWith("AI_"))
  .map(([id, meta]) => ({ id, ...meta }));
